name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: snapshot.jar
          # Directory containing files to upload
          path: modules/cli/target/cli-1.0-SNAPSHOT.jar
