name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    -   name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
            # Artifact name
            name: snapshot.jar
            # Directory containing files to upload
            path: modules/cli/target/cli-1.0-SNAPSHOT.jar
